main = "./src/index.ts"
compatibility_date = "2022-11-11"
workers_dev = true
# logpush = true
# node_compat = true
minify = true


[env.dev]
name = "note-reward-manager-dev"

[env.dev.vars]
NETWORK = "Mainnet"
MANAGER_BOT_ADDRESS = "0x3164400d0c849996efCb390ec1D4705f2cD5E98C"

[env.beta]
name = "note-reward-manager-beta"

[env.prod]
name = "note-reward-manager"

# [triggers]
# crons = ["0/10 * * * *"]
