account_id = '274f86c6dcfbb77c09e49e86d101c753'
main = "./src/index.ts"
compatibility_date = "2022-11-11"
workers_dev = true
logpush = true
# node_compat = true
minify = true


[env.dev]
name = "note-reward-manager-dev"

[env.dev.vars]
NETWORK = "mainnet"
MANAGER_BOT_ADDRESS = "0x745915418D8B70f39ce9e61A965cBB0C87f9f7Ed"

[env.beta]
name = "note-reward-manager-beta"

[env.prod]
name = "note-reward-manager"

[triggers]
# Run two times every other hour at Sunday, once to sell comp tokens and then again to burn note
crons = ["0 */2 * * 1", "10 */2 * * 1"]
