main = "./src/index.ts"
compatibility_date = "2022-11-11"
workers_dev = true
# logpush = true
# node_compat = true
minify = true


[env.dev]
name = "note-reward-manager-dev"

[env.dev.vars]
NETWORK = "mainnet"
ZERO_EX_API_URL = "https://api.0x.org/swap/v1/quote"
# it has 'arbitrum' in url but it is also endpoint for mainnet relayers,
# endpoint format is "/v1/txes/:relayerId", relayerId 0 is for arbitrum an 1 for mainnet
TX_RELAY_SEND_URL = "https://tx-relay-arbitrum-dot-monitoring-agents.uc.r.appspot.com/v1/txes/1"

[env.beta]
name = "note-reward-manager-beta"

[env.prod]
name = "note-reward-manager"

# [triggers]
# crons = ["0/10 * * * *"]
