name: Deploy V2 Website
on:
  workflow_dispatch:
  push:
    branches:
      - v2/prod
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Yarn Install
        run: yarn install --frozen-lockfile
      - name: Build Web
        run: yarn nx build web --parallel
        env:
          NX_BLOCK_NATIVE_DAPP_ID: ${{ secrets.NX_BLOCK_NATIVE_DAPP_ID }}
          NX_CONTACT_EMAIL: ${{ secrets.NX_CONTACT_EMAIL }}
          NX_DD_APP_ID: ${{ secrets.NX_DD_APP_ID }}
          NX_DD_API_KEY: ${{ secrets.NX_DD_API_KEY }}
          NX_DD_BASE_URL: ${{ secrets.NX_DD_BASE_URL }}
          NX_DD_SITE: ${{ secrets.NX_DD_SITE }}
          NX_GOOGLE_ANALYTICS_ID: ${{ secrets.NX_GOOGLE_ANALYTICS_ID }}
          NX_INFURA_KEY: ${{ secrets.NX_INFURA_KEY }}
          NX_APP_URL: ${{ secrets.NX_APP_URL }}
          NX_SYSTEM_CACHE_URL: ${{ secrets.NX_SYSTEM_CACHE_URL }}
          NX_ALCHEMY_KEY: ${{ secrets.NX_ALCHEMY_KEY }}
          NX_EXCHANGE_RATE_API: ${{ secrets.NX_EXCHANGE_RATE_API }}
          NX_SUBGRAPH_API_KEY: ${{ secrets.NX_SUBGRAPH_API_KEY }}
          NX_ENV: ${{ github.event.inputs.environment || 'dev' }}
          NX_COMMIT_REF: ${{ github.sha }}
      - name: Publish Dev
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: notional-web-v2-prod
          directory: dist/apps/web
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}